//Auth Types
export const LOAD = "LOAD";

export const REGISTER_MSG = "REGISTER_MSG";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const COINMARKETCAP_SUCCESS = "COINMARKETCAP_SUCCESS";
export const COINMARKETCAP_FAIL = "COINMARKETCAP_FAIL";
export const MIDGARDPOOL_SUCCESS = "MIDGARDPOOL_SUCCESS";
export const MIDGARDPOOL_FAIL = "MIDGARDPOOL_FAIL";
